#!/bin/bash

# CommandGuard
# Prevent execution of dangerous git commands without confirmation.

# Check this cutomization is enabled.
enabled=$(lnxcstm git -g -e)
if [[ "$enabled" =~ "False" ]]; then
	/usr/bin/git $@
	exit
fi

CMD="$1"

alert() {
    /usr/bin/git status
    # Check confirmation is enabled.
    confirmation_enable=$(lnxcstm git -g -c)
    if [[ "$confirmation_enable" =~ "True" ]]; then
	read -rn1 -p "$(echo -e "Do you want to continue \033[1;33m${CMD}\033[0m ? [Y/n]: ")" confirmation # Get the confirmation from user before initiate.
    	echo
    	if [[ ! "$confirmation" =~ ^[yY] ]]; then
        	echo "Abort git $CMD.."
        	exit 1
	fi	
    fi

    # Authenticate User
    authentication_enable=$(lnxcstm git -g -a)
    if [[ "$authentication_enable" =~ "True" ]]; then
    	echo "Authentication required to continue.."
	sudo -vk || exit 1
    fi
}

case "$CMD" in
    checkout|rm|reset|clean|rebase|push)
        alert
        ;;
esac

# Execute git command
/usr/bin/git "$@"
