#!/bin/bash

# CommandGuard
# Prevent execution of dangerous git commands without confirmation.

CMD="$1"

alert() {
    /usr/bin/git status
    read -rn1 -p "$(echo -e "Do you want to continue \033[1;33m${CMD}\033[0m ? [Y/n]")" confirmation # Get the confirmation from user before initiate.
    echo
    if [[ ! "$confirmation" =~ ^[yY] ]]; then
        echo "Abort git $CMD.."
        exit 1
    fi

    # Confirming User
    echo "Authentication required to continue..."
    sudo -vk || exit 1 
}

case "$CMD" in
    checkout|rm|reset|clean|rebase|push)
        alert
        ;;
esac

# Execute git command
/usr/bin/git "$@"
